default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  <<: *default
development:
  <<: *default
  secret_key_base:  be1e6dffe1d1720e541ad7a3db9265464955e306576d0f10c8b06ac70a13313ff3e9d8da75118baaafa6a6d18fcc534872e049d2ebb551bed96e3228d8190de9

staging:
  <<: *default
production:
  <<: *default
